if(DEFINED ENV{MSFS_SDK} AND IS_DIRECTORY "$ENV{MSFS_SDK}")
  set(MSFS_SDK_FOUND TRUE)
  find_file(MSFS_SDK_VERSION_FILE
    "version.txt"
    PATHS "$ENV{MSFS_SDK}"
    NO_CACHE
  )
  cmake_path(GET MSFS_SDK_VERSION_FILE PARENT_PATH MSFS_SDK_ROOT_DIR)
  set(MSFS_SDK_ROOT_DIR "${MSFS_SDK_ROOT_DIR}"
    CACHE PATH "Microsoft Flight Simulator SDK root directory path"
  )
  file(STRINGS "${MSFS_SDK_VERSION_FILE}" MSFS_SDK_VERSION_FILE_CONTENT)
  list(GET MSFS_SDK_VERSION_FILE_CONTENT 0 MSFS_SDK_VERSION_STRING)
  string(STRIP "${MSFS_SDK_VERSION_STRING}" MSFS_SDK_VERSION_STRING)
  unset(MSFS_SDK_VERSION_FILE)
  unset(MSFS_SDK_VERSION_FILE_CONTENT)
  set(MSFS_SDK_VERSION ${MSFS_SDK_VERSION_STRING})
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MSFS_SDK
  FOUND_VAR MSFS_SDK_FOUND
  REQUIRED_VARS
    MSFS_SDK_ROOT_DIR
  VERSION_VAR MSFS_SDK_VERSION
  HANDLE_VERSION_RANGE
)
