if(DEFINED ENV{MSFS_SDK} AND IS_DIRECTORY "$ENV{MSFS_SDK}")
  set(MSFS_SDK_FOUND TRUE)
  cmake_path(CONVERT "$ENV{MSFS_SDK}" TO_CMAKE_PATH_LIST MSFS_SDK_ROOT_DIR NORMALIZE)
  cmake_path(CONVERT "${MSFS_SDK_ROOT_DIR}/version.txt" TO_CMAKE_PATH_LIST MSFS_SDK_VERSION_FILE_PATH NORMALIZE)
  get_filename_component(MSFS_SDK_ROOT_DIR ${MSFS_SDK_VERSION_FILE_PATH} DIRECTORY)
  file(STRINGS ${MSFS_SDK_VERSION_FILE_PATH} MSFS_SDK_VERSION_FILE_CONTENT)
  list(GET MSFS_SDK_VERSION_FILE_CONTENT 0 MSFS_SDK_VERSION_STRING)
  string(STRIP ${MSFS_SDK_VERSION_STRING} MSFS_SDK_VERSION_STRING)
  set(MSFS_SDK_VERSION ${MSFS_SDK_VERSION_STRING})
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MSFS_SDK
  FOUND_VAR MSFS_SDK_FOUND
  REQUIRED_VARS
    MSFS_SDK_ROOT_DIR
  VERSION_VAR MSFS_SDK_VERSION
  HANDLE_VERSION_RANGE
)
