# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  abi:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
      - name: Download MSFS SDK Core Installer
        shell: pwsh
        run: "& ./.github/scripts/DownloadMSFS_SDK.ps1 -Verbose"
      - name: Execute MSFS SDK Core Installer
        shell: pwsh
        run: "& ./.github/scripts/ExecuteMSFS_SDKInstaller.ps1 -Verbose"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore tools
        run: dotnet tool restore

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
