on:
  workflow_call:
    inputs:
      create-pr:
        type: boolean
        default: false
      version:
        type: string
      long-version:
        type: string
      msi-url:
        type: string

jobs:
  simconnect:
    runs-on: windows-latest
    name: Generate SimConnect ABI from MSFS_SDK
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
      - name: Git configure comitter identity
        uses: thnetii/.github/actions/git-user-config@main
      - id: checkout-pr-branch
        name: Swich to new PR branch
        uses: thnetii/github-actions/run/create-rebase-pr-branch@main
        with:
          branch-name: msfs_sdk/v${{ inputs.version }}

      - id: download-msfs-sdk
        name: Download MSFS SDK
        shell: pwsh
        run: >
          & .\.github\scripts\DownloadMSFS_SDK.ps1 -Verbose
          -Version $ENV:MSFS_SDK_VERSION
          -LongVersion $ENV:MSFS_SDK_LONGVERSION
          -DownloadUrl $ENV:MSFS_SDK_INSTALLER_URL
        env:
          MSFS_SDK_VERSION: ${{ inputs.version }}
          MSFS_SDK_LONGVERSION: ${{ inputs.long-version }}
          MSFS_SDK_INSTALLER_URL: ${{ inputs.msi-url }}
      - id: install-msfs-sdk
        name: Install MSFS SDK
        shell: pwsh
        run: >
          & .\.github\scripts\ExecuteMSFS_SDKInstaller.ps1 -Verbose
          -MsiPath $ENV:MSFS_SDK_INSTALLER_PATH
        env:
          MSFS_SDK_INSTALLER_PATH: ${{ steps.download-msfs-sdk.outputs.msi-installer-path }}

      - name: Restore .NET tools
        uses: thnetii/github-actions/run/gh-actions-exec@main
        with:
          command: dotnet
          arguments: |
            tool
            restore
