on:
  push:
    branches: ["main"]

jobs:
  init:
    name: Analyse MSFS SDK versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
      - id: get-matrix
        name: Analyse well-known versions
        shell: pwsh
        run: "& ./.github/scripts/GetGitHubActionsMSFS_SDKMatrix.ps1 -Verbose"
    outputs:
      msfs-sdk-matrix: ${{ steps.get-matrix.outputs.msfs-sdk-matrix }}

  generate:
    needs: init
    strategy:
      matrix: ${{ fromJson(needs.init.outputs.msfs-sdk-matrix) }}
    uses: ./.github/workflows/msfs_sdk_generate-abi.yml
    name: "MSFS SDK v${{ matrix.version }}"
    with:
      version: ${{ matrix.version }}
      long-version: ${{ matrix.long-version }}
      msi-url: ${{ matrix.msi-url }}
      create-pr: true
